language: node_js
node_js:
  - "18"
cache:
  directories:
    - node_modules

branches:
  only:
    - main
    - develop

install:
  - npm ci

before_script:
  - npm run build

script:
  - npm test

notifications:
  email:
    recipients:
      - your-email@example.com
    on_success: change
    on_failure: always
